#!/usr/bin/env python3
"""生成Mock术语内容，用于API失败兜底。"""
import json
from pathlib import Path
from datetime import datetime

BASE = Path(__file__).parent.parent
SEED_FILE = BASE / "data" / "seeds" / "seed_terms.json"
OUTPUT_DIR = BASE / "data" / "mock"
LANGS = ["en", "es", "de", "ja", "fr", "zh"]


def generate_mock_term(term, lang):
    """为单个术语生成Mock内容。"""
    if lang == "en":
        name = term["english"]
        short_def = f"[Mock] {term['english']} is a key concept in AI, specifically in the {term['category'].replace('_', ' ')} domain."
        long_def = f"[Mock] This is a placeholder definition for {term['english']}. The actual definition will be generated by AGNES_LLM. This term belongs to the {term['category']} category and has an importance rating of {term['importance']}/5."
    else:
        name = term["english"]  # Mock阶段保留英文
        short_def = f"[Mock/{lang}] {term['english']} es un concepto clave en IA."
        long_def = f"[Mock/{lang}] This is a placeholder translation for {term['english']}."
    return {
        "term_id": term["term_id"],
        "language": lang,
        "term_name": name,
        "definition_short": short_def,
        "definition_long": long_def,
        "key_concepts": ["concept_1", "concept_2", "concept_3"],
        "use_cases": ["use_case_1", "use_case_2"],
        "related_terms": ["related_1", "related_2"],
        "code_example": None,
        "difficulty": 3,
        "tags": [term["category"], "mock"],
        "source": "mock",
        "generated_at": datetime.utcnow().isoformat() + "Z",
    }


def main():
    with open(SEED_FILE, "r", encoding="utf-8") as f:
        seeds = json.load(f)
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    # 仅为前20个术语生成Mock（节省时间，后续按需生成）
    for term in seeds[:20]:
        for lang in LANGS:
            mock = generate_mock_term(term, lang)
            out_file = OUTPUT_DIR / f"{term['term_id']}_{lang}.json"
            with open(out_file, "w", encoding="utf-8") as f:
                json.dump(mock, f, ensure_ascii=False, indent=2)
    print(f"已为前20个术语生成Mock数据 × {len(LANGS)} 语种 = {20*len(LANGS)} 文件")


if __name__ == "__main__":
    main()
